### ISSUE TITLE
Python Data Visualization Tour app does not load

### ISSUE THREAD

**Issue by youssofr** [discdiver/data-viz-streamlit#4] opened 2021-07-23 11:21 UTC
This message shows when I try to open [Gallery --> Dta Visualization --> Python Tour](https://share.streamlit.io/discdiver/data-viz-streamlit/main/app.py)
![image](https://user-images.githubusercontent.com/20542475/126760875-0d6fa7e9-4eb2-4dd4-8344-ff2fbeacb15a.png)
 
I am located in Cairo, Egypt.

**Comment by discdiver** [comment] 2021-08-12 19:40
Thank you for sitting  Works for me now. Closing, as not reproducible. Perhaps streamlit was down?

**Closed as completed by discdiver** 2021-08-12 19:40 UTC
